import type { AIProvider, GenerateOptions } from "../ai-provider";

/**
 * Mock AI Provider for testing
 * Returns structured JSON output without calling external AI
 */
export class MockProvider implements AIProvider {
  name = "mock";

  async generate(prompt: string, options?: GenerateOptions): Promise<string> {
    // Parse prompt to extract output file paths
    const outputSection = prompt.match(/## Output Files \(Your Task\)\s+You must generate or update these files:\s+((?:- .+\n?)+)/);
    const outputFiles: string[] = [];

    if (outputSection) {
      const lines = outputSection[1].trim().split('\n');
      for (const line of lines) {
        const match = line.match(/^- (.+)$/);
        if (match) {
          outputFiles.push(match[1]);
        }
      }
    }

    // Extract slice ID
    const sliceIdMatch = prompt.match(/- Slice ID: (.+)/);
    const sliceId = sliceIdMatch ? sliceIdMatch[1] : "unknown";

    // Extract existing requirement IDs from prompt
    const reqMatches = prompt.match(/REQ-[A-Z]+-\d+/g) || [];
    const existingReqs = [...new Set(reqMatches)];

    // Extract existing scenario IDs from prompt (look for Scenario: lines in behaviors.feature)
    const scenarioLines = prompt.match(/Scenario: (.+)/g) || [];
    const existingScenarios: string[] = [];

    // Generate scenario IDs from scenario titles
    for (const line of scenarioLines) {
      const title = line.replace('Scenario: ', '').trim();
      // Convert "Successful checkout creates an order" -> "SCN-ORDER-CHECKOUT-VALID"
      // Convert "Checkout rejects an unavailable item" -> "SCN-ORDER-CHECKOUT-OUT-OF-STOCK"
      const scnId = title.toLowerCase().includes('reject') || title.toLowerCase().includes('unavailable')
        ? 'SCN-ORDER-CHECKOUT-OUT-OF-STOCK'
        : 'SCN-ORDER-CHECKOUT-VALID';
      if (!existingScenarios.includes(scnId)) {
        existingScenarios.push(scnId);
      }
    }

    // Infer artifact type and gate from output file
    const inferArtifactType = (fileName: string): string => {
      const mapping: Record<string, string> = {
        "requirements.md": "requirement",
        "invariants.md": "invariant",
        "behaviors.feature": "scenario",
        "test-spec.yaml": "test",
        "design.md": "design",
      };
      const baseName = fileName.split('/').pop() || fileName;
      return mapping[baseName] || "artifact";
    };

    const inferGate = (fileName: string): string | null => {
      const mapping: Record<string, string> = {
        "requirements.md": "requirements_ready",
        "design.md": "design_ready",
        "behaviors.feature": "behavior_ready",
        "test-spec.yaml": "test_ready",
        "evidence.md": "verification_ready",
      };

      const baseName = fileName.split('/').pop() || fileName;

      // Check if it's a directory (ends with / or is just "src")
      if (fileName.endsWith('/') || fileName === 'src') {
        return "implementation_ready";
      }

      return mapping[baseName] || null;
    };

    // Generate content based on file type
    const generateContent = (file: string): string => {
      const baseName = file.split('/').pop() || file;

      if (baseName === "test-spec.yaml") {
        // Generate valid test-spec.yaml
        const tests = existingScenarios.map((scnId, idx) => {
          const testId = `TEST-${scnId.replace('SCN-', '')}-INTEGRATION`;
          return {
            id: testId,
            type: "integration",
            verifies: [scnId],
            target: "checkout-service"
          };
        });

        return `tests:\n${tests.map(t =>
          `  - id: ${t.id}\n    type: ${t.type}\n    verifies:\n      - ${t.verifies[0]}\n    target: ${t.target}`
        ).join('\n')}`;
      }

      return `# Mock output for ${file}\n\nGenerated by MockProvider for slice: ${sliceId}\n`;
    };

    // Separate files and directories
    const files = outputFiles.filter(f => !f.endsWith('/') && f !== 'src');
    const directories = outputFiles.filter(f => f.endsWith('/') || f === 'src');

    // Generate writes for files
    const writes = files.map(file => ({
      path: file,
      content: generateContent(file),
      encoding: "utf-8"
    }));

    // Generate writeOperations for directories
    const writeOperations = directories.map(dir => ({
      type: "directory" as const,
      path: dir.endsWith('/') ? dir : `${dir}/`,
    }));

    // Generate trace links for outputs
    const traceLinks = outputFiles.flatMap(file => {
      const baseName = file.split('/').pop() || file;
      const artifactType = inferArtifactType(baseName);

      if (baseName === "test-spec.yaml" && existingScenarios.length > 0) {
        // Generate trace links from scenarios to tests
        return existingScenarios.map(scnId => {
          const testId = `TEST-${scnId.replace('SCN-', '')}-INTEGRATION`;
          return {
            from: { type: "scenario", id: scnId },
            to: { type: "test", id: testId },
            relation: "covered_by"
          };
        });
      }

      return [];
    });

    // Generate gate updates for outputs (only for known gates)
    const gateUpdates = outputFiles
      .map(file => {
        const gate = inferGate(file);
        if (!gate) return null;
        return {
          gate,
          passed: true,
          reason: "Mock provider auto-pass"
        };
      })
      .filter((update): update is { gate: string; passed: boolean; reason: string } => update !== null);

    // Generate structured output
    const output = {
      success: true,
      writes,
      writeOperations,
      gateUpdates,
      traceLinks,
      evidence: [
        {
          type: "agent_execution",
          content: JSON.stringify({ provider: "mock", sliceId }),
          timestamp: new Date().toISOString()
        }
      ]
    };

    return JSON.stringify(output, null, 2);
  }

  async isAvailable(): Promise<boolean> {
    return true;
  }
}
