import type { AIProvider, GenerateOptions } from "../ai-provider";
import { createDirectoryIdentity, fromPath } from "../artifact-identity";

/**
 * Mock AI Provider for testing
 * Returns structured JSON output without calling external AI
 */
export class MockProvider implements AIProvider {
  name = "mock";

  async generate(prompt: string, options?: GenerateOptions): Promise<string> {
    if (prompt.includes("## Bootstrap Draft Mode")) {
      return JSON.stringify(buildBootstrapDraftBundle(prompt), null, 2);
    }

    // Test hook: increment call counter if specified
    if (process.env.JISPEC_TEST_CALL_COUNTER_FILE) {
      const fs = await import('node:fs');
      const counterFile = process.env.JISPEC_TEST_CALL_COUNTER_FILE;
      let count = 0;
      if (fs.existsSync(counterFile)) {
        count = parseInt(fs.readFileSync(counterFile, 'utf-8'), 10) || 0;
      }
      fs.writeFileSync(counterFile, String(count + 1), 'utf-8');
    }

    // Parse prompt to extract output file paths
    const outputSection = prompt.match(/## Output Files \(Your Task\)\s+You must generate or update these files:\s+((?:- .+\n?)+)/);
    const outputFiles: string[] = [];

    if (outputSection) {
      const lines = outputSection[1].trim().split('\n');
      for (const line of lines) {
        const match = line.match(/^- (.+)$/);
        if (match) {
          outputFiles.push(match[1]);
        }
      }
    }

    // Extract slice ID
    const sliceIdMatch = prompt.match(/- Slice ID: (.+)/);
    const sliceId = sliceIdMatch ? sliceIdMatch[1] : "unknown";

    // Extract context ID from prompt
    const contextIdMatch = prompt.match(/- Context ID: (.+)/);
    const contextId = contextIdMatch ? contextIdMatch[1] : null;

    // Extract stage ID from prompt
    const stageIdMatch = prompt.match(/- Stage: (.+)/);
    const stageId = stageIdMatch ? stageIdMatch[1] : "unknown";

    // Extract existing requirement IDs from prompt
    const reqMatches = prompt.match(/REQ-[A-Z]+-\d+/g) || [];
    const existingReqs = [...new Set(reqMatches)];

    // Extract existing scenario IDs from prompt (look for Scenario: lines in behaviors.feature)
    const scenarioLines = prompt.match(/Scenario: (.+)/g) || [];
    const existingScenarios: string[] = [];

    // Generate scenario IDs from scenario titles
    for (const line of scenarioLines) {
      const title = line.replace('Scenario: ', '').trim();
      // Convert "Successful checkout creates an order" -> "SCN-ORDERING-PAYMENT-V1-VALID"
      // Convert "Checkout rejects an unavailable item" -> "SCN-ORDERING-PAYMENT-V1-INVALID"
      const scnId = title.toLowerCase().includes('reject') || title.toLowerCase().includes('unavailable')
        ? `SCN-${sliceId.toUpperCase().replace(/-/g, '-')}-INVALID`
        : `SCN-${sliceId.toUpperCase().replace(/-/g, '-')}-VALID`;
      if (!existingScenarios.includes(scnId)) {
        existingScenarios.push(scnId);
      }
    }

    // Infer artifact type and gate from output file
    const inferArtifactType = (fileName: string): string => {
      const mapping: Record<string, string> = {
        "requirements.md": "requirement",
        "invariants.md": "invariant",
        "behaviors.feature": "scenario",
        "test-spec.yaml": "test",
        "design.md": "design",
      };
      const baseName = fileName.split('/').pop() || fileName;
      return mapping[baseName] || "artifact";
    };

    const inferGate = (fileName: string): string | null => {
      const mapping: Record<string, string> = {
        "requirements.md": "requirements_ready",
        "design.md": "design_ready",
        "behaviors.feature": "behavior_ready",
        "test-spec.yaml": "test_ready",
        "evidence.md": "verification_ready",
      };

      const baseName = fileName.split('/').pop() || fileName;

      // Check if it's a directory (ends with / or is just "src")
      if (fileName.endsWith('/') || fileName === 'src') {
        return "implementation_ready";
      }

      return mapping[baseName] || null;
    };

    // Generate content based on file type
    const generateContent = (file: string): string => {
      const baseName = file.split('/').pop() || file;

      if (baseName === "requirements.md") {
        // Generate requirements.md with proper requirement IDs
        const reqId = `REQ-${sliceId.toUpperCase().replace(/-/g, '-')}-001`;
        return `# Requirements for ${sliceId}

## Functional Requirements

### ${reqId}: Core Functionality
The system shall provide the core functionality for ${sliceId}.

**Acceptance Criteria:**
- AC1: System accepts valid inputs
- AC2: System produces expected outputs
- AC3: System handles error cases gracefully

**Priority:** High
**Status:** Draft
`;
      }

      if (baseName === "output.txt") {
        // Generate simple output for generic output files
        return `Mock output for ${sliceId}\nGenerated by requirements stage\n`;
      }

      if (baseName === "design.md") {
        // Generate design.md
        return `# Design for ${sliceId}

## Architecture Overview
This slice implements the core functionality using a service-oriented architecture.

## Components
- **Service Layer**: Handles business logic
- **Data Layer**: Manages persistence
- **API Layer**: Exposes endpoints

## Data Flow
1. Request received at API layer
2. Service layer processes request
3. Data layer persists changes
4. Response returned to client

## Technology Stack
- TypeScript
- Node.js
- Express
`;
      }

      if (baseName === "behaviors.feature") {
        // Generate behaviors.feature with proper scenario IDs
        const scnId1 = `SCN-${sliceId.toUpperCase().replace(/-/g, '-')}-VALID`;
        const scnId2 = `SCN-${sliceId.toUpperCase().replace(/-/g, '-')}-INVALID`;
        return `Feature: ${sliceId}

  Scenario: ${scnId1} - Valid operation
    Given a valid input
    When the operation is performed
    Then the result is successful

  Scenario: ${scnId2} - Invalid operation
    Given an invalid input
    When the operation is performed
    Then an error is returned
`;
      }

      if (baseName === "test-spec.yaml") {
        // Generate valid test-spec.yaml
        const tests = existingScenarios.map((scnId, idx) => {
          // Extract service name from slice ID: "ordering-payment-v1" -> "payment-service"
          const serviceName = sliceId.split('-').slice(1, -1).join('-') + '-service';
          const testId = `TEST-${scnId.replace('SCN-', '')}-INTEGRATION`;
          return {
            id: testId,
            type: "integration",
            verifies: [scnId],
            target: serviceName
          };
        });

        return `tests:\n${tests.map(t =>
          `  - id: ${t.id}\n    type: ${t.type}\n    verifies:\n      - ${t.verifies[0]}\n    target: ${t.target}`
        ).join('\n')}`;
      }

      return `# Mock output for ${file}\n\nGenerated by MockProvider for slice: ${sliceId}\n`;
    };

    // Separate files and directories
    const files = outputFiles.filter(f => !f.endsWith('/') && f !== 'src');
    const directories = outputFiles.filter(f => f.endsWith('/') || f === 'src');

    // Generate writes for files with identity
    const writes = files.map(file => {
      // Use stageId from prompt, not 'unknown'
      const actualStageId = stageId !== 'unknown' ? stageId : 'requirements';
      const identity = fromPath(file, actualStageId);
      return {
        path: file,
        content: generateContent(file),
        encoding: "utf-8",
        identity
      };
    });

    // For src directory, also generate a sample implementation file
    if (directories.some(d => d === 'src' || d.endsWith('src/'))) {
      const srcDir = directories.find(d => d === 'src' || d.endsWith('src/'));
      const srcPath = srcDir === 'src' ? 'src/' : srcDir;

      // Extract service name from slice ID: "ordering-payment-v1" -> "payment-service"
      const serviceName = sliceId.split('-').slice(1, -1).join('-') + '-service';
      const className = serviceName.split('-').slice(0, -1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('') + 'Service';

      const srcFilePath = `${srcPath}${serviceName}.ts`;
      const srcIdentity = fromPath(srcFilePath, stageId);

      writes.push({
        path: srcFilePath,
        content: `// Mock implementation for ${sliceId}\n\nexport class ${className} {\n  async process(input: string): Promise<string> {\n    // Mock implementation\n    return "result-123";\n  }\n}\n`,
        encoding: "utf-8",
        identity: srcIdentity
      });
    }

    // Generate writeOperations for directories
    const writeOperations = directories.map(dir => {
      const dirPath = dir.endsWith('/') ? dir : `${dir}/`;
      const dirIdentity = createDirectoryIdentity(dirPath, sliceId, stageId);
      return {
        type: "directory" as const,
        path: dirPath,
        identity: dirIdentity
      };
    });

    // Generate trace links for outputs
    const traceLinks = outputFiles.flatMap(file => {
      const baseName = file.split('/').pop() || file;

      if (baseName === "requirements.md") {
        // Generate trace links to register requirements in trace.yaml
        // Requirements trace from slice to requirement artifacts
        const reqId = `REQ-${sliceId.toUpperCase().replace(/-/g, '-')}-001`;
        return [{
          from: { type: "slice", id: sliceId },
          to: { type: "requirement", id: reqId },
          relation: "requires"
        }];
      }

      if (baseName === "design.md") {
        // Generate trace link from requirement to design
        const reqId = `REQ-${sliceId.toUpperCase().replace(/-/g, '-')}-001`;
        return [{
          from: { type: "requirement", id: reqId },
          to: { type: "design", id: "design.md" },
          relation: "designed_by"
        }];
      }

      if (baseName === "behaviors.feature") {
        // Generate trace links from requirements to scenarios
        const reqId = `REQ-${sliceId.toUpperCase().replace(/-/g, '-')}-001`;
        const scnId1 = `SCN-${sliceId.toUpperCase().replace(/-/g, '-')}-VALID`;
        const scnId2 = `SCN-${sliceId.toUpperCase().replace(/-/g, '-')}-INVALID`;
        return [
          {
            from: { type: "requirement", id: reqId },
            to: { type: "scenario", id: scnId1 },
            relation: "verified_by"
          },
          {
            from: { type: "requirement", id: reqId },
            to: { type: "scenario", id: scnId2 },
            relation: "verified_by"
          }
        ];
      }

      if (baseName === "test-spec.yaml" && existingScenarios.length > 0) {
        // Generate trace links from scenarios to tests
        return existingScenarios.map(scnId => {
          const testId = `TEST-${scnId.replace('SCN-', '')}-INTEGRATION`;
          return {
            from: { type: "scenario", id: scnId },
            to: { type: "test", id: testId },
            relation: "covered_by"
          };
        });
      }

      // For src directory, generate trace links from tests to code
      if (file === 'src' || file.endsWith('src/')) {
        if (existingScenarios.length > 0) {
          // Extract service name from slice ID: "ordering-payment-v1" -> "payment-service"
          const serviceName = sliceId.split('-').slice(1, -1).join('-') + '-service';
          const srcPath = file === 'src' ? 'src/' : file;
          return existingScenarios.map(scnId => {
            const testId = `TEST-${scnId.replace('SCN-', '')}-INTEGRATION`;
            return {
              from: { type: "test", id: testId },
              to: { type: "code", id: `src/${serviceName}` },
              relation: "implemented_by"
            };
          });
        }
      }

      return [];
    });

    // Generate gate updates for outputs (only for known gates)
    const gateUpdates = outputFiles
      .map(file => {
        const gate = inferGate(file);
        if (!gate) return null;
        return {
          gate,
          passed: true,
          reason: "Mock provider auto-pass"
        };
      })
      .filter((update): update is { gate: string; passed: boolean; reason: string } => update !== null);

    // Generate structured output
    const output = {
      success: process.env.JISPEC_TEST_INJECT_FAILURE === 'true' ? false : true,
      error: process.env.JISPEC_TEST_INJECT_FAILURE === 'true' ? 'Injected test failure' : undefined,
      writes,
      writeOperations,
      gateUpdates,
      traceLinks,
      evidence: [
        {
          type: "agent_execution",
          content: JSON.stringify({ provider: "mock", sliceId }),
          timestamp: new Date().toISOString(),
          identity: {
            sliceId,
            stageId,
            artifactType: "evidence",
            artifactId: "mock-execution"
          }
        }
      ]
    };

    return JSON.stringify(output, null, 2);
  }

  async isAvailable(): Promise<boolean> {
    return true;
  }
}

function buildBootstrapDraftBundle(prompt: string): {
  artifacts: Array<{
    kind: "domain" | "api" | "feature";
    relativePath: string;
    content: string;
    sourceFiles: string[];
    confidenceScore: number;
    provenanceNote: string;
  }>;
  warnings: string[];
} {
  const summaryMatch = prompt.match(/## Ranked Evidence Summary\s+```json\s*([\s\S]+?)\s*```/);
  const rankedSummary = summaryMatch ? safeParseJSON(summaryMatch[1]) : undefined;
  const graphMatch = prompt.match(/## Evidence Graph JSON\s+```json\s*([\s\S]+?)\s*```/);
  const graph = graphMatch ? safeParseJSON(graphMatch[1]) : undefined;
  const rankedRouteSignals = Array.isArray(rankedSummary?.routeSignalsUsed) ? rankedSummary.routeSignalsUsed.slice(0, 4) : [];
  const rankedSchemaSignals = Array.isArray(rankedSummary?.schemaSignalsUsed) ? rankedSummary.schemaSignalsUsed.slice(0, 4) : [];
  const rankedTestSignals = Array.isArray(rankedSummary?.testSignalsUsed) ? rankedSummary.testSignalsUsed.slice(0, 4) : [];
  const topDocumentPaths = Array.isArray(rankedSummary?.documentSignalsUsed)
    ? rankedSummary.documentSignalsUsed.map((entry: string) => entry.split(" (")[0]).slice(0, 3)
    : [];
  const topManifestPaths = Array.isArray(rankedSummary?.manifestSignalsUsed)
    ? rankedSummary.manifestSignalsUsed.map((entry: string) => entry.split(" (")[0]).slice(0, 2)
    : [];
  const rankedRouteKeys = rankedRouteSignals
    .map((entry: string) => {
      const match = entry.match(/^([A-Z]+)\s+(\S+)/);
      return match ? `${match[1]} ${match[2]}` : undefined;
    })
    .filter((value: string | undefined): value is string => typeof value === "string");
  const rankedSchemaPaths = rankedSchemaSignals
    .map((entry: string) => entry.split(" (")[0])
    .filter((value: string) => value.length > 0);
  const rankedTestPaths = rankedTestSignals
    .map((entry: string) => entry.split(" (")[0])
    .filter((value: string) => value.length > 0);
  const rankedRoutes = Array.isArray(graph?.routes)
    ? [...graph.routes].sort((left: any, right: any) => {
        const leftKey = `${String(left?.method || "UNKNOWN").toUpperCase()} ${String(left?.path || "/")}`;
        const rightKey = `${String(right?.method || "UNKNOWN").toUpperCase()} ${String(right?.path || "/")}`;
        const leftIndex = rankedRouteKeys.indexOf(leftKey);
        const rightIndex = rankedRouteKeys.indexOf(rightKey);
        if (leftIndex !== -1 || rightIndex !== -1) {
          if (leftIndex === -1) return 1;
          if (rightIndex === -1) return -1;
          return leftIndex - rightIndex;
        }
        return leftKey.localeCompare(rightKey);
      })
    : [];
  const rankedSchemas = Array.isArray(graph?.schemas)
    ? [...graph.schemas].sort((left: any, right: any) => {
        const leftIndex = rankedSchemaPaths.indexOf(String(left?.path || ""));
        const rightIndex = rankedSchemaPaths.indexOf(String(right?.path || ""));
        if (leftIndex !== -1 || rightIndex !== -1) {
          if (leftIndex === -1) return 1;
          if (rightIndex === -1) return -1;
          return leftIndex - rightIndex;
        }
        return String(left?.path || "").localeCompare(String(right?.path || ""));
      })
    : [];
  const rankedTests = Array.isArray(graph?.tests)
    ? [...graph.tests].sort((left: any, right: any) => {
        const leftIndex = rankedTestPaths.indexOf(String(left?.path || ""));
        const rightIndex = rankedTestPaths.indexOf(String(right?.path || ""));
        if (leftIndex !== -1 || rightIndex !== -1) {
          if (leftIndex === -1) return 1;
          if (rightIndex === -1) return -1;
          return leftIndex - rightIndex;
        }
        return String(left?.path || "").localeCompare(String(right?.path || ""));
      })
    : [];
  const sourceFiles = uniqueSorted([
    ...rankedRoutes.slice(0, 4).flatMap((route: any) => route.sourceFiles || []),
    ...rankedSchemas.slice(0, 4).map((schema: any) => schema.path),
    ...rankedTests.slice(0, 4).map((test: any) => test.path),
    ...topDocumentPaths,
    ...topManifestPaths,
  ]);
  const primaryContexts = Array.isArray(rankedSummary?.primaryContextNames) ? rankedSummary.primaryContextNames : [];
  const evidenceStrength = typeof rankedSummary?.evidenceStrength === "string" ? rankedSummary.evidenceStrength : "moderate";

  const domainContent = `metadata:
  source_files:
${sourceFiles.slice(0, 8).map((file) => `    - ${file}`).join("\n") || "    - bootstrap/evidence-graph.json"}
  confidence_score: 0.81
  provenance_note: Mock provider synthesized this domain draft from ranked bootstrap evidence.
domain:
  repo_root: ${graph?.repoRoot || "unknown"}
  evidence_strength: ${evidenceStrength}
  primary_contexts:
${primaryContexts.map((name: string) => `    - ${name}`).join("\n") || "    - bootstrap"}
  route_count: ${Array.isArray(graph?.routes) ? graph.routes.length : 0}
  schema_count: ${Array.isArray(graph?.schemas) ? graph.schemas.length : 0}
  test_count: ${Array.isArray(graph?.tests) ? graph.tests.length : 0}`;

  const apiEndpoints = rankedRoutes.length > 0
    ? rankedRoutes.slice(0, 4).map((route: any, index: number) => {
        const supportingSchemas = rankedSchemas
          .filter((schema: any) => routeMatchesArtifact(route, schema?.path))
          .slice(0, 3)
          .map((schema: any) => ({
            path: schema.path,
            format: schema.format || "unknown",
          }));
        return ({
        id: `${String(route.method || "unknown").toLowerCase()}-route-${index + 1}`,
        method: route.method || "UNKNOWN",
        path: route.path || `/draft-${index + 1}`,
        source_files: uniqueSorted(route.sourceFiles || []),
        confidence_score: 0.79,
        provenance_note: "Mock provider synthesized this endpoint from bootstrap route evidence.",
        supporting_schemas: supportingSchemas,
      });
      })
    : [
        {
          id: "unknown-route-1",
          method: "UNKNOWN",
          path: "/",
          source_files: sourceFiles.slice(0, 3),
          confidence_score: 0.45,
          provenance_note: "Mock provider synthesized a placeholder endpoint because no route evidence was found.",
        },
      ];

  const featureLines = [
    `# source_files: ${JSON.stringify(sourceFiles.slice(0, 6))}`,
    "# confidence_score: 0.76",
    "# provenance_note: Mock provider synthesized this feature draft from ranked bootstrap evidence.",
    "Feature: Bootstrap drafted behaviors",
    "",
  ];

  const featureRoutes = rankedRoutes.slice(0, 2);
  if (featureRoutes.length > 0) {
    for (const route of featureRoutes) {
      const routeKey = `${String(route.method || "UNKNOWN").toUpperCase()} ${String(route.path || "/")}`;
      const relatedTest = rankedTests.find((test: any) => routeMatchesArtifact(route, test?.path));
      featureLines.push(`  Scenario: ${routeKey} remains reviewable during adoption`);
      featureLines.push(`    Given bootstrap discover prioritized ${routeKey}`);
      featureLines.push(`    And supporting source files include "${(route.sourceFiles || [])[0] || sourceFiles[0] || "unknown"}"`);
      if (relatedTest?.path) {
        featureLines.push(`    And test evidence includes "${relatedTest.path}"`);
      }
      featureLines.push("    When the first contract bundle is reviewed");
      featureLines.push("    Then the drafted behavior stays available for adoption");
      featureLines.push("");
    }
  } else {
    featureLines.push("  Scenario: Drafted contract remains visible to adopters");
    featureLines.push(
      `    Given bootstrap discover prioritized ${rankedRouteSignals[0] || `${Array.isArray(graph?.routes) ? graph.routes.length : 0} route candidates`}`,
    );
    featureLines.push(`    And supporting source files include "${sourceFiles[0] || "unknown"}"`);
    featureLines.push("    When the first contract bundle is reviewed");
    featureLines.push("    Then the drafted behavior stays available for adoption");
  }

  return {
    artifacts: [
      {
        kind: "domain",
        relativePath: "drafts/domain.yaml",
        content: domainContent,
        sourceFiles: sourceFiles.slice(0, 10),
        confidenceScore: 0.81,
        provenanceNote: "Mock provider synthesized this domain draft from bootstrap evidence.",
      },
      {
        kind: "api",
        relativePath: "drafts/api_spec.json",
        content: JSON.stringify(
          {
            metadata: {
              source_files: sourceFiles.slice(0, 10),
              confidence_score: 0.79,
              provenance_note: "Mock provider synthesized this API draft from bootstrap evidence.",
            },
            api_spec: {
              title: "Mock Bootstrap API Draft",
              version: "0.1.0-draft",
              endpoints: apiEndpoints,
            },
          },
          null,
          2,
        ),
        sourceFiles: sourceFiles.slice(0, 10),
        confidenceScore: 0.79,
        provenanceNote: "Mock provider synthesized this API draft from bootstrap evidence.",
      },
      {
        kind: "feature",
        relativePath: "drafts/behaviors.feature",
        content: featureLines.join("\n"),
        sourceFiles: sourceFiles.slice(0, 10),
        confidenceScore: 0.76,
        provenanceNote: "Mock provider synthesized this feature draft from bootstrap evidence.",
      },
    ],
    warnings: [],
  };
}

function safeParseJSON(input: string): any {
  try {
    return JSON.parse(input);
  } catch {
    return undefined;
  }
}

function uniqueSorted(values: string[]): string[] {
  return [...new Set(values.filter((value) => typeof value === "string" && value.length > 0))].sort((left, right) =>
    left.localeCompare(right),
  );
}

function routeMatchesArtifact(route: any, candidatePath: string | undefined): boolean {
  if (!candidatePath || typeof route?.path !== "string") {
    return false;
  }

  const keywords = extractRouteKeywords(route.path);
  const lowerCandidatePath = candidatePath.toLowerCase();
  return keywords.some((keyword) => lowerCandidatePath.includes(keyword));
}

function extractRouteKeywords(routePath: string): string[] {
  const words = routePath
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((part) => part.length >= 3 && !["api", "v1", "v2", "health", "status"].includes(part));
  const expanded = new Set<string>();

  for (const word of words) {
    expanded.add(word);
    if (word.endsWith("ies") && word.length > 4) {
      expanded.add(`${word.slice(0, -3)}y`);
    }
    if (word.endsWith("s") && word.length > 4) {
      expanded.add(word.slice(0, -1));
    } else if (word.length > 3) {
      expanded.add(`${word}s`);
    }
  }

  return [...expanded];
}
