import type { AIProvider, GenerateOptions } from "../ai-provider";

/**
 * Mock AI Provider for testing
 * Returns structured JSON output without calling external AI
 */
export class MockProvider implements AIProvider {
  name = "mock";

  async generate(prompt: string, options?: GenerateOptions): Promise<string> {
    // Parse prompt to extract output file paths
    const outputSection = prompt.match(/## Output Files \(Your Task\)\s+You must generate or update these files:\s+((?:- .+\n?)+)/);
    const outputFiles: string[] = [];

    if (outputSection) {
      const lines = outputSection[1].trim().split('\n');
      for (const line of lines) {
        const match = line.match(/^- (.+)$/);
        if (match) {
          outputFiles.push(match[1]);
        }
      }
    }

    // Extract slice ID
    const sliceIdMatch = prompt.match(/- Slice ID: (.+)/);
    const sliceId = sliceIdMatch ? sliceIdMatch[1] : "unknown";

    // Generate structured output
    const output = {
      success: true,
      writes: outputFiles.map(file => ({
        path: file,
        content: `# Mock output for ${file}\n\nGenerated by MockProvider for slice: ${sliceId}\n`,
        encoding: "utf-8"
      })),
      gateUpdates: [
        {
          gate: "requirements_defined",
          passed: true,
          reason: "Mock provider auto-pass"
        }
      ],
      traceLinks: [],
      evidence: [
        {
          type: "agent_execution",
          content: JSON.stringify({ provider: "mock", sliceId }),
          timestamp: new Date().toISOString()
        }
      ]
    };

    return JSON.stringify(output, null, 2);
  }

  async isAvailable(): Promise<boolean> {
    return true;
  }
}
