import path from "node:path";
import type { ImplementRunResult } from "../implement/implement-runner";
import type { CompletionEvidence, CompletionEvidenceStatus, DisciplineCommandEvidence, DisciplineTruthSource } from "./types";

export function buildCompletionEvidence(result: ImplementRunResult, generatedAt = new Date().toISOString(), root?: string): CompletionEvidence {
  const commands: DisciplineCommandEvidence[] = [];
  const truthSources: DisciplineTruthSource[] = [];

  if (result.metadata.testCommand) {
    commands.push({
      command: result.metadata.testCommand,
      exitCode: result.testsPassed === undefined ? null : result.testsPassed ? 0 : 1,
      ranAt: generatedAt,
      evidenceKind: "test",
      summary: result.testsPassed ? "Mediated test command passed." : "Mediated test command did not pass.",
    });
  }

  if (result.postVerify?.command) {
    commands.push({
      command: result.postVerify.command,
      exitCode: result.postVerify.exitCode,
      ranAt: generatedAt,
      evidenceKind: "verify",
      summary: `Post-implement verify returned ${result.postVerify.verdict}.`,
    });
  }

  if (result.metadata.handoffPacketPath) {
    truthSources.push({
      path: normalizeArtifactPath(result.metadata.handoffPacketPath, root),
      provenance: "EXTRACTED",
      note: "Implementation handoff packet generated by JiSpec.",
    });
  }
  if (result.metadata.patchMediationPath) {
    truthSources.push({
      path: normalizeArtifactPath(result.metadata.patchMediationPath, root),
      provenance: "EXTRACTED",
      note: "Patch mediation artifact generated by JiSpec.",
    });
  }

  const missingEvidence = computeMissingEvidence(result);

  return {
    schemaVersion: 1,
    kind: "jispec-agent-completion-evidence",
    sessionId: result.sessionId,
    generatedAt,
    status: computeCompletionStatus(result, missingEvidence),
    commands,
    verifyCommand: result.postVerify?.command ?? result.metadata.verifyCommand,
    verifyVerdict: result.postVerify?.verdict,
    missingEvidence,
    truthSources,
  };
}

function normalizeArtifactPath(artifactPath: string, root?: string): string {
  if (!root) {
    return artifactPath.replace(/\\/g, "/");
  }
  return path.isAbsolute(artifactPath)
    ? path.relative(root, artifactPath).replace(/\\/g, "/")
    : artifactPath.replace(/\\/g, "/");
}

function computeCompletionStatus(result: ImplementRunResult, missingEvidence: string[]): CompletionEvidenceStatus {
  if (result.outcome === "patch_rejected_out_of_scope" || result.outcome === "verify_blocked") {
    return "blocked";
  }
  if (result.outcome === "external_patch_received" && result.testsPassed === false) {
    return "blocked";
  }
  if (result.outcome === "budget_exhausted" || result.outcome === "stall_detected") {
    return "owner_review_required";
  }
  if (!result.postVerify) {
    return missingEvidence.length > 0 ? "ready_for_verify" : "incomplete";
  }
  if (!result.postVerify.ok) {
    return "blocked";
  }
  return result.postVerify.advisoryIssueCount > 0 ? "verified_with_advisory" : "verified";
}

function computeMissingEvidence(result: ImplementRunResult): string[] {
  const missing: string[] = [];
  if (!result.metadata.testCommand) {
    missing.push("test command missing");
  }
  if (!result.postVerify) {
    missing.push("verify result missing");
  }
  return missing;
}
